trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

jobs:
  - template: azure-pipelines-template.yml
    parameters:
      name: macOS
      vmImage: macOS-10.13

  - template: azure-pipelines-template.yml
    parameters:
      name: Alpine_Linux
      vmImage: ubuntu-16.04
      container: node:lts-alpine
  
  - template: azure-pipelines-template.yml
    parameters:
      name: CentOS_Linux
      vmImage: ubuntu-16.04
      container: prebuild/centos7-devtoolset7

  - template: azure-pipelines-template.yml
    parameters:
      name: Windows
      vmImage: windows-2019

  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
    - job: Publish
      condition: succeeded()
      dependsOn:
        - macOS
        - Linux
        - Windows
      pool: 
        vmImage: ubuntu-16.04
      steps:
        - task: DownloadBuildArtifacts@0
          displayName: Download Artifacts
          inputs:
            artifactName: prebuilds
            downloadPath: "$(System.DefaultWorkingDirectory)"
        - task: GitHubRelease@0
          displayName: Github Release
          inputs:
            gitHubConnection: parcel
            repositoryName: parcel-bundler/watcher
            assets: $(System.DefaultWorkingDirectory)/prebuilds/@parcel/*
        - task: Npm@1
          displayName: NPM Release
          inputs:
            command: 'publish'
            publishEndpoint: npm
