jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
    maxParallel: 3
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  # Install Watchman
  - ${{ if eq(parameters.name, 'macOS') }}:
    - script: |
        brew update
        brew install watchman
      displayName: Install Watchman

  - ${{ if eq(parameters.name, 'Linux') }}:
    - script: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get purge libc6-dev
        sudo apt-get install -y gcc-7 g++-7 libc6-dev
        # git clone https://github.com/facebook/watchman.git
        # cd watchman
        # git checkout v4.9.0
        # ./autogen.sh
        # ./configure
        # make
        # sudo make install
      displayName: Install Watchman

  - script: yarn
    displayName: 'Install dependencies'
  - script: yarn test
    displayName: 'Run tests'
