jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  - ${{ if eq(parameters.name, 'Linux') }}:
    - container: jotadrilo/watchman
  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
    maxParallel: 3
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  # Install Watchman
  - ${{ if eq(parameters.name, 'macOS') }}:
    - script: |
        brew update
        brew install watchman
      displayName: Install Watchman

  - script: yarn
    displayName: 'Install dependencies'
  - script: yarn test
    displayName: 'Run tests'
