jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  ${{ if eq(parameters.name, 'Linux') }}:
    container: jotadrilo/watchman:latest
  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
    maxParallel: 3
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  # Install Watchman
  - ${{ if eq(parameters.name, 'macOS') }}:
    - script: |
        brew update
        brew install watchman
      displayName: Install Watchman

  - ${{ if eq(parameters.name, 'Windows') }}:
    - script: |
        curl -sSf -L -o watchman.zip https://ci.appveyor.com/api/buildjobs/vkp4mmk1cri9jsel/artifacts/watchman.zip
      displayName: Download Watchman
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: 'watchman.zip'
        destinationFolder: $(Agent.HomeDirectory)
        cleanDestinationFolder: false
      displayName: Extract Watchman
    - script: |
        set PATH=%PATH%;$(Agent.HomeDirectory)\watchman
        echo "##vso[task.setvariable variable=PATH]%PATH%"
        watchman -v
      displayName: Install Watchman

  - script: npm install
    displayName: 'Install dependencies'
  - script: npm test
    displayName: 'Run tests'
